package com.sptinc

/* This class defines the log in and general information of each User.
* This class was automatically generated by the Spring Security Grails plugin, with some additional modifications.
*/
class User {
	String username // The login name
	String password // This is encrypted by the controller
	String fullName
	String email
	Company company // Each User is associated with a company
	boolean enabled // Spring Sec flags follow
	boolean accountExpired
	boolean accountLocked
	boolean passwordExpired

	Date dateCreated
	Date lastUpdated
	
	// Each User can be assigned to many Roles through the UserRole join table
	// Each User can be assigned many contracts
	static hasMany = [contracts: Contract, userRoles: UserRole]
	// These values are not persisted
	static transients = ['name']

	static constraints = {
		username(blank: false, unique: true, maxSize: 10)
		password(blank: false)
		email(email: true, blank: false)
		company(blank: false)
	}

	// Spring Sec password mapping
	static mapping = {
		password column: '`password`'
	}

	// Get all of the Roles for this User
	Set<Role> getAuthorities() {
		UserRole.findAllByUser(this).collect { it.role } as Set
	}

	// Get all of the Trips for this User
    Set<Trip> getTrips() {
		UserTrip.findAllByAttendee(this).collect { it.attendee } as Set
	}

	String toString() {
	    return fullName + " @ " + company
	}
	
	String getName() {
		return this.toString()
	}

	def beforeInsert() {
	    dateCreated = new Date()
    }
    def beforeUpdate() {
        lastUpdated = new Date()
    }
}
